management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

server:
  port: 8680
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

eureka:
   instance:
     preferIpAddress: true
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://eurekaserver:8580/eureka/ 

spring:
  application:
    name: WebGateway
  lifecycle:
    timeout-per-shutdown-phase: 15s  
  cloud:
    gateway:
      routes:
      - id: orders-route
        uri: lb://CHECKOUT #${checkout_SERVICE_URL:http://checkout:8080}
        predicates:
        - Path=/orders/**
        filters:
        - RewritePath=/orders/?(?<segment>.*), /api/orders/$\{segment}
  security:
    user:
      name: admin
      password: admin
      
                
     
  
